### PR TITLE
Bump asciidoctor-epub3 to 1.5.0.alpha.11

### PR DESCRIPTION
**Pull request by slonopotamus**
Release notes for alpha-10: https://github.com/asciidoctor/asciidoctor-epub3/releases/tag/v1.5.0.alpha.10
Release notes for alpha-11: https://github.com/asciidoctor/asciidoctor-epub3/releases/tag/v1.5.0.alpha.11

### CODE REVIEW

**Comment by jnavila** [comment]
Thanks, are there any known limitations to this bump, before I switch to asciidoctor 2.0.10?

**Comment by slonopotamus** [comment]
It was discovered that alpha-11 doesn't respect `KINDLEGEN` environment variable when generates KF8/Mobi: https://github.com/asciidoctor/asciidoctor-epub3/issues/269

Workarounds are:
1. Wait for alpha-12
2. Use alpha-10
3. Use alpha-11 with `kindlegen` gem

**Comment by jnavila** [comment]
I choose solution 1: wait... We're not in a hurry.

**Comment by slonopotamus** [comment]
Makes sense, okay.

**Pull request closed without merging**
